name: Secuential execution

on:
  workflow_dispatch:
    
jobs:
  greeting_job:
    runs-on: Linux
    steps:
    - name: Hello world
      run: echo Hello, world!
  sequential_job:
      runs-on: Linux
      needs: [greeting_job]
      steps:
      - name: Greeting secuential job
        run: echo right after greeting!
